#!/bin/sh
# BM: Bookmarks
# Author: Nan0Scho1ar (Christopher Mackinga)
# Created: 17/10/2020
# License: MIT License

add() { read -p "Enter key: " key; read -p "Enter value: " val; echo "$key~|~$val" >> $1; }
delete() { sed -i $(cat -n $1 | fzy | sed "s/\(\s*[0-9]*\).*/\1d/") $1; }
readval() { cat "$1" | fzy | sed "s/.*~|~//"; }

mkdir -p ~/.config/bookmarks/;
if [ -z $1 ]; then readval $(ls $HOME/.config/bookmarks/*.bm | fzy);
elif [ "$1" = "add" ]; then add "$HOME/.config/bookmarks/$2.bm";
elif [ "$1" = "delete" ]; then delete "$HOME/.config/bookmarks/$2.bm";
else readval "$HOME/.config/bookmarks/$1.bm";
fi
