#!/bin/sh
# CB: cd bookmarks
# Author: Nan0Scho1ar (Christopher Mackinga)
# Created: 31/08/2021
# License: GPL v3

cb() {
    #TODO Prompt for missing args
    case "$1" in
        add) echo -e "$2\n$(pwd)" | bm add dirs;;
        rm) bm rm "$2" dirs;;
        list) bm list dirs;;
        reload) source "$NREPOS/n0s1.core/cb";;
        *) cd $(bm get "$1" dirs);;
    esac
}
