#!/bin/sh
# EF: Edit bookmarked files
# Author: Nan0Scho1ar (Christopher Mackinga)
# Created: 31/08/2021
# License: GPL v3

ef() {
    #TODO Prompt for missing args
    case "$1" in
        add) echo -e "$2\n$(pwd)/$3" | bm add editfiles;;
        rm) bm rm "$2" editfiles;;
        list) bm list editfiles;;
        reload) source "$NREPOS/n0s1.core/ef" && echo "Reloaded ef";;
        *) vim $(bm get "$1" editfiles);;
    esac
}
