#!/bin/sh
# HIST: Shell history made easy
# Author: Nan0Scho1ar (Christopher Mackinga)
# Created: 06/11/2020
# License: MIT License

[ $SHELL = "/bin/zsh" ] &&
    histfile="$XDG_CONFIG_HOME/zsh/.zhistory" ||
    histfile="$HOME/.history"

sep="; "
cmdlist="$1"

if [ -z "$1" ]; then
    cat --number "$histfile" | less
    exit
elif [ "$1" = '-a' ]; then
    sep=" && "
    cmdlist="$2"
elif [[ "$1" =~ "-h|--help" ]]; then
    echo "hist            list history"
    echo "hist 50..55     run cmd list ; seperated"
    echo "hist -a 50..55  run cmd list && seperated"
    exit
fi
# 50..55
if [[ $cmdlist =~ ^[0-9]+\.\.[0-9]+$ ]]; then
    START="$(echo $cmdlist | sed 's/^\([0-9]*\)\.\.\([0-9]*\)$/\1/')"
    END="$(echo $cmdlist | sed 's/^\([0-9]*\)\.\.\([0-9]*\)$/\2/')"
    final=""
    for i in $(eval echo "{$START..$END}"); do
        cmd=$(cat --number $histfile | sed -n "s/^\s*${i}\t\(.*\)/\1/p")
        [ -z "$cmd" ] && final="$cmd" || final="$final$sep$cmd"
    done
    echo "$final"
    eval "$final"
fi
