#!/bin/sh
# LESS: The hackable less
# Author: Nan0Scho1ar (Christopher Mackinga)
# Created: 30/10/2020
# License: MIT License

hackless() {
    [ -z $1 ] && lines="$(echo "$(< /dev/stdin)")" || lines="$(cat "$1")";
    numlines="$(echo "$lines" | wc -l)" && height="$(tput lines)" && \
    echo -e "\e[?1049h" && row=1 && regex="" || return 1
    while true; do
        row2="$((row+height-2))";
        echo "$lines" | sed -n "$row,${row2}p;${row2}q" | \
            grep --colour=always "^\|$regex" | cut -c "$col-9999"
        lastline="$([[ $numlines -ge $height ]] && echo $((numlines-height+2)))"
        [[ $row -eq $lastline ]] && cur="$(tput rev)END$(tput sgr0)" || cur=":"
        read -sn1 -p "$cur" < /dev/tty char && echo -e "$(tput el1)\r"
        case $char in
            'q') echo -e "\e[?1049l" && return;;
            'k') [[ $row -gt 1 ]] && row=$((row-1));;
            'j') [[ $row -lt $lastline ]] && row=$((row+1));;
            'h') [[ $row -gt 1 ]] && col=$((col-1));;
            'l') col=$((col+1));;
            'g') row=1;;
            'G') row=$lastline;;
            '/') read -p "/" < /dev/tty regex
        esac
    done
}
