#!/bin/bash
# mkexecdir: Make all files in current directory which begin with a shebang executable
# Author: Nan0Scho1ar (Christopher Mackinga)
# Created: Wed 17 Nov 2021 15:06:27 AEST
# License: GPL v3
# Copyright (C) 2021 Christopher Mackinga <chris@n0s1.net>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of  MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.

green=`tput setaf 2`
reset=`tput sgr0`

while IFS= read -r fname; do
    head="$(head -n1 "$fname")"
    if [[ $head =~ ^#! ]]; then
        echo -e "$green$fname$reset:\t$head"
        chmod +x "$fname"
    fi
done < <(ls -F | grep -v "/$") | column -ts $'\t'
