#!/bin/bash
# Ingest a directory full of files to tangled script blocks in a org file.

dir="$([ -z $1 ] && pwd || echo $1)"
while IFS= read -r fname; do
    echo "* $fname"
    echo "#+begin_src sh :tangle $fname"
    cat "$fname"
    echo "#+end_src"
    echo
done < <(ls -p "$dir" | grep -v /)
