#!/bin/bash
# tmux_setup: Installs tmux plugin manager
# Author: Nan0Scho1ar (Christopher Mackinga)
# Created: Tue 26 Oct 2021 19:41:50 AEST
# License: GPL v3
# Copyright (C) 2021 Christopher Mackinga <chris@n0s1.net>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of  MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.

tmux_setup() {
    if [ -d "$HOME/.tmux/plugins" ];then
        echo "tmux plugin manager (tpm) already installed"
    elif ask "Install tmux plugin manager"; then
        mkdir -p $HOME/.tmux/plugins/
        git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    fi
}
