#!/bin/bash
#AUTHOR: Nan0Scho1ar
#License: GPL v3
#Script for running nested tmux sessions
#Calls recursively to add additional information

case $1 in
    sys)
        toomuxh system $HOME/repos/dotfiles/tmux/sys.sh $2
        ;;
    local)
        TMUX= ;
        toomuxh $HOSTNAME $HOME/repos/dotfiles/tmux/local.sh $2
        ;;
    cluster)
        TMUX= ;
        toomuxh ${HOSTNAME}_C $HOME/repos/dotfiles/tmux/cluster.sh $2
        ;;
    *)
        SESSION="$1"
        CONFIG="$2"
        case $3 in
            q|quit|Q|QUIT|Quit|exit|Exit)
                if tmux has-session -t $SESSION 2>/dev/null; then
                    tmux kill-session -t $SESSION 2>/dev/null &&
                        echo "Killed tmux session '$SESSION'" ||
                        echo "Failed to kill tmux session '$SESSION'"
                else
                    echo "Tmux session '$SESSION' does not exist"
                fi
                exit
                ;;
            *)
                if tmux has-session -t $SESSION 2>/dev/null; then
                    tmux -2 attach-session -t $SESSION 2>/dev/null ||
                    echo "Failed to attach tmux session '$SESSION'"
                else
                    tmux -2 new-session -s $SESSION $CONFIG
                fi
                ;;
        esac
        ;;
esac
