#!/bin/bash
# trylink: Tries to create a symlink
# Author: Nan0Scho1ar (Christopher Mackinga)
# Created: Tue 26 Oct 2021 19:32:19 AEST
# License: GPL v3
# Copyright (C) 2021 Christopher Mackinga <chris@n0s1.net>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of  MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.


trylink() {
    if [ "$(diff -q "$1" "$2")" != "" ]; then
        ask "${magenta}$2${reset} already exists and is not identical. Show diff" &&
            diff "$1" "$2"
        ask "Remove ${red}$2${reset}" && rm "$2"
    else
        rm "$2"
    fi
    echo "Linking ${magenta}$2${reset}"
    ln -sf "$1" "$2"
}
