#!/bin/bash
# ubuntu_pkg_setup: Script to install ubuntu packages
# Author: Nan0Scho1ar (Christopher Mackinga)
# Created: Tue 26 Oct 2021 19:39:47 AEST
# License: GPL v3
# Copyright (C) 2021 Christopher Mackinga <chris@n0s1.net>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of  MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.


ubuntu_pkg_setup() {
    tryaptinstall ripgrep
    tryaptinstall fzf
    tryaptinstall keychain
    tryaptinstall tmux
    tryaptinstall curl
    tryaptinstall youtube-dl
    tryaptinstall vim
    tryaptinstall neovim
    tryaptinstall nodejs
    tryaptinstall zsh

    tryaptinstall fd-find
    #fd is already used on Ubuntu
    if dpkg-query -W -f='${Status}' fd-find 2> /dev/null | grep -q "install ok installed"; then
        asklink "fdfind (ubuntu fix)" "$(which fdfind)" "$HOME/.local/bin/fd"
    fi
    #Bat is not in standard repos because reasons
    if dpkg-query -W -f='${Status}' bat 2> /dev/null | grep -q "install ok installed"; then
        echo "${green}bat${reset} is already installed"
    elif ask "'${magenta}bat${reset}' is not installed, would you like to install it"; then
        cur_dir=$(pwd)
        cd /tmp
        wget https://github.com/sharkdp/bat/releases/download/v0.17.1/bat_0.17.1_amd64.deb
        sudo dpkg -i bat_0.17.1_amd64.deb
        cd $cur_dir
    fi
    ###TODO Install Rider
}
